# Generated by Django 4.2.27 on 2026-02-10 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('recommendation_id', models.CharField(db_index=True, max_length=64)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'recommendation_feedback',
            },
        ),
        migrations.CreateModel(
            name='LocationContext',
            fields=[
                ('location_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'location_context',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('item_id', models.CharField(db_index=True, max_length=64)),
                ('item_type', models.CharField(max_length=16)),
                ('score', models.FloatField()),
                ('reason_type', models.CharField(choices=[('interest', 'Interest'), ('location', 'Location'), ('popularity', 'Popularity')], max_length=16)),
                ('reason_description', models.TextField(blank=True)),
                ('user_feedback', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('none', 'None')], default='none', max_length=16)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('interaction_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('item_id', models.CharField(db_index=True, max_length=64)),
                ('item_type', models.CharField(choices=[('article', 'Article'), ('place', 'Place'), ('event', 'Event'), ('route', 'Route')], max_length=16)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('rate', 'Rate'), ('added_to_plan', 'AddedToPlan'), ('rejected', 'Rejected')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_interactions',
            },
        ),
        migrations.CreateModel(
            name='UserProfileFeature',
            fields=[
                ('feature_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('weight', models.FloatField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('interaction', 'Interaction')], max_length=32)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_profile_features',
            },
        ),
    ]
